USE [master]
GO

/****** Object:  Database [languages]    Script Date: 21/01/2019 11:53:44 ******/
CREATE DATABASE [languages]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'languages', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\languages.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'languages_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\languages_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [languages] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [languages].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [languages] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [languages] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [languages] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [languages] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [languages] SET ARITHABORT OFF 
GO

ALTER DATABASE [languages] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [languages] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [languages] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [languages] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [languages] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [languages] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [languages] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [languages] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [languages] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [languages] SET  DISABLE_BROKER 
GO

ALTER DATABASE [languages] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [languages] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [languages] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [languages] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [languages] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [languages] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [languages] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [languages] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [languages] SET  MULTI_USER 
GO

ALTER DATABASE [languages] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [languages] SET DB_CHAINING OFF 
GO

ALTER DATABASE [languages] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [languages] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [languages] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [languages] SET  READ_WRITE 
GO


