USE [master]
GO

/****** Object:  Database [webDevelopment]    Script Date: 21/01/2019 13:38:05 ******/
CREATE DATABASE [students]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'students', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\students.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'students_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\students_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [students] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [students].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [students] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [students] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [students] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [students] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [students] SET ARITHABORT OFF 
GO

ALTER DATABASE [students] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [students] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [students] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [students] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [students] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [students] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [students] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [students] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [students] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [students] SET  DISABLE_BROKER 
GO

ALTER DATABASE [students] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [students] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [students] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [students] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [students] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [students] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [students] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [students] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [students] SET  MULTI_USER 
GO

ALTER DATABASE [students] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [students] SET DB_CHAINING OFF 
GO

ALTER DATABASE [students] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [students] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [students] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [students] SET  READ_WRITE 
GO


